apiVersion: v1
kind: Service
metadata:
  name: log-analyser-unmanaged
  namespace: log-analyser
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: tcp
    port: 8008
    protocol: TCP
    targetPort: tcp
  selector:
    camel.apache.org/integration: log-analyser
  sessionAffinity: None
  type: ClusterIP